### ISSUE TITLE
Start function do not work when working with a pool of CoreOs behind load-balancer(F5).

### ISSUE THREAD

**Issue by edanShavit** [lukebond/fleetctl-ssh#1]
Hi Luke,
We have use your library in many cases and we are very pleased with the result.

All our development were done on a relative small setup in which we have access the remote Fleet directly.
We are deploying our product on large production setup with multiple CoreOS machines in the Fleet.
In order to provide redundancy in the Fleet we can not access any CoreOS machine directly and we need to use load balancer like F5.

In the large setup we have notice that sometimes the Start command is failing without any obvious reason.
When debugging the library we have notice that the Start fleet command was separated to 2 parts:
1. scp command - copy the unit file to the remote machine.
2. ssh & fleet start - start the unit file we have just copied.

because we work with load-balancer, we can not promise that these two commands will run on a same CoreOS machine. The use-case is as follow:
the unit-file was copied to one machine, and start command for this service were run on another machine  ==> the unit-file wasn't found.

We have change the code to run the two commands in single SSH connection.

here is our change on our forked repository:
https://github.com/att-innovate/fleetctl-ssh/commit/107b0792cd81cd186ba1c4ea47144059a14a9821
We would like you to add it to your library.

best regards,
Yehudit Shternfeld
Edan Shavit

**Comment by lukebond** [comment]
Sorry for the delay, I'm away atm. Glad you're finding it useful and thanks for the contribution. When I'm back home I'll merge it in and make another NPM release.

**Comment by lukebond** [comment]
@edanShavit would you mind sending a PR please?

**Comment by edanShavit** [comment]
done

**Comment by lukebond** [comment]
Thanks. Merged and released on NPM.
